# NumPy

In der vorherigen Lektion haben wir uns mit Listen beschäftigt. Diese sind sehr flexibel, aber auch sehr langsam. Mit kleinen Listen werden wir das nicht merken, aber wenn wir mit großen Datenmengen arbeiten, dann кönnen lange Laufzeiten zum Problem werden. 

NumPy (Numerical Python) ist ein Paket, das viele Funktionen enthält, die wir für die Arbeit mit großen Datenmengen geeignet sind.

In [5]:
import numpy as np
from time import process_time

In [6]:
# Wir können eine Liste in ein NumPy-Array umwandeln
a_list = range(int(1e6))
a_array = np.array(a_list)

In [7]:
start_zeit = process_time()

a_list_plus_2 = [i + 2 for i in a_list]

end_zeit = process_time()
round(end_zeit - start_zeit, 5)

0.72373

In [8]:
start_zeit_1 = process_time()

a_array_plus_2 = a_array + 2

end_zeit_1 = process_time()
round(end_zeit_1 - start_zeit_1, 5)

0.01351

In [14]:
x = np.array([2, 7, 5, 2])
y = np.ones(4)
y

array([1., 1., 1., 1.])

NumPy-Arrays sind sehr ähnlich zu Listen, aber sie haben einige zusätzliche Eigenschaften. Zum Beispiel können wir mit NumPy-Arrays rechnen. Wenn wir zwei NumPy-Arrays addieren, dann werden die Elemente an der gleichen Stelle addiert. Diese Syntax ist sehr intuitiv und einfach zu lesen.


In [15]:
z1 = x + 1 
z2 = x + y
z1

array([3, 8, 6, 3])

In [16]:
z2

array([3., 8., 6., 3.])

Dasselbe funktioniert mit Python-Listen nicht. Wenn wir zwei Listen addieren, dann werden die Elemente an der gleichen Stelle nicht addiert, sondern die Listen werden aneinander gehängt.

In [17]:
x_list = [2, 7, 5, 2]
y_list = [1, 1, 1, 1]
x_list + y_list

[2, 7, 5, 2, 1, 1, 1, 1]

In [18]:
x_list + 1

TypeError: can only concatenate list (not "int") to list

NumPy-Arrays haben auch einige Methoden, die wir mit Listen nicht haben. Zum Beispiel können wir die Summe aller Elemente eines Arrays berechnen.

In [19]:
x.sum()

16

In [20]:
x.mean()

4.0

In [21]:
x.std()

2.1213203435596424

In [22]:
x.min()

2

In [ ]:
x.max()

In [23]:
x.argmin()

0

In [24]:
x.argmax()

1

Wir können auch auf die Elemente eines Arrays zugreifen, indem wir einen Index angeben. Der Index beginnt bei 0.

In [25]:
x[0]

2

In [26]:
x[:2]

array([2, 7])

In [29]:
x[-3]

array([7, 5, 2])

In [30]:
x[-3:]

array([7, 5, 2])

In [31]:
x[1:3]

array([7, 5])

In [32]:
x[::2]

array([2, 5])

In [33]:
x[::-1]

array([2, 5, 7, 2])

In [35]:
x[1] = 10
x

array([ 2, 10,  5,  2])